/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package newpackage;

import javax.swing.JOptionPane;

/**
 *
 * @author ADMIN
 */
public class SignUp_Page1 extends javax.swing.JFrame {

    /**
     * Creates new form Log1
     */
    public SignUp_Page1() {
        initComponents();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        UsernameSignTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        PasswordSignUpTextfield = new javax.swing.JPasswordField();
        SignUpPageBtn = new javax.swing.JButton();
        LoginSignUpBtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        EmailSignUpTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(710, 540));
        setPreferredSize(new java.awt.Dimension(800, 440));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Baskerville Old Face", 1, 26)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Smart Activity Monitoring");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 300, 49));

        jLabel6.setFont(new java.awt.Font("Baskerville Old Face", 1, 26)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("System");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 80, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("( College Name )");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 320, 490));

        jLabel1.setFont(new java.awt.Font("Perpetua Titling MT", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("Sign Up");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 50, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel2.setText("Username :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 200, -1, -1));

        UsernameSignTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsernameSignTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(UsernameSignTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 230, 240, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel3.setText("Password :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 270, -1, -1));

        PasswordSignUpTextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordSignUpTextfieldActionPerformed(evt);
            }
        });
        getContentPane().add(PasswordSignUpTextfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 300, 240, -1));

        SignUpPageBtn.setBackground(new java.awt.Color(0, 102, 102));
        SignUpPageBtn.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        SignUpPageBtn.setForeground(new java.awt.Color(255, 255, 255));
        SignUpPageBtn.setText("Sign Up");
        SignUpPageBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignUpPageBtnActionPerformed(evt);
            }
        });
        getContentPane().add(SignUpPageBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 350, -1, 40));

        LoginSignUpBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LoginSignUpBtn.setForeground(new java.awt.Color(255, 51, 51));
        LoginSignUpBtn.setText("Login");
        LoginSignUpBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        LoginSignUpBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginSignUpBtnActionPerformed(evt);
            }
        });
        getContentPane().add(LoginSignUpBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 400, 53, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel5.setText("Email :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 130, -1, -1));

        EmailSignUpTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailSignUpTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(EmailSignUpTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 160, 240, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PasswordSignUpTextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordSignUpTextfieldActionPerformed
        // TODO add your handling code here:
        if(PasswordSignUpTextfield.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Please Enter Correct field !");
        }
    }//GEN-LAST:event_PasswordSignUpTextfieldActionPerformed

    private void UsernameSignTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernameSignTextFieldActionPerformed
        // TODO add your handling code here:
        if(UsernameSignTextField.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Please Enter Correct field !");
        }
    }//GEN-LAST:event_UsernameSignTextFieldActionPerformed

    private void SignUpPageBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignUpPageBtnActionPerformed
        // TODO add your handling code here:
        
        JOptionPane.showMessageDialog(null, "Sign Up Successfully !");
        
    }//GEN-LAST:event_SignUpPageBtnActionPerformed

    private void LoginSignUpBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginSignUpBtnActionPerformed
        // TODO add your handling code here:
        dispose();
        Login_Page1 lg = new Login_Page1();
        lg.setVisible(true);
    }//GEN-LAST:event_LoginSignUpBtnActionPerformed

    private void EmailSignUpTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailSignUpTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailSignUpTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp_Page1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp_Page1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp_Page1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp_Page1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUp_Page1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField EmailSignUpTextField;
    private javax.swing.JButton LoginSignUpBtn;
    private javax.swing.JPasswordField PasswordSignUpTextfield;
    private javax.swing.JButton SignUpPageBtn;
    private javax.swing.JTextField UsernameSignTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
